import type {
  DemoAttachment,
  DemoConversation,
  DemoCreator,
  DemoMessage,
  DemoProduct,
  DemoSubscriber,
  DemoVaultItem,
} from "./types";

export const DEMO_CHATTER = "Sam Rivera";
export const NOW = "2026-09-01T14:12:00.000Z";

export const demoCreators: DemoCreator[] = [
  { id: "creator_maya", displayName: "Maya Voss", handle: "maya_voss", style: "Playful GFE" },
  { id: "creator_elena", displayName: "Elena Hart", handle: "elena_hart", style: "Dominant" },
  { id: "creator_jade", displayName: "Jade Wren", handle: "jade_wren", style: "Bratty" },
  { id: "creator_lila", displayName: "Lila Brooks", handle: "lila_brooks", style: "Romantic GFE" },
];

const synced = "2026-08-30T18:00:00.000Z";

export const demoVault: DemoVaultItem[] = [
  { id: "media_engagement", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "PHOTO", title: "Engagement pic", description: "Cheap hello still. First PPV.", tags: ["engagement", "tease"], placeholderKind: "PHOTO_SET", defaultPrice: 8, minimumPrice: 8, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_engagement" },
  { id: "media_engagement_prev", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "PHOTO", title: "Engagement preview", description: "Blurred hello still.", tags: ["preview", "engagement"], placeholderKind: "FREE_PREVIEW", defaultPrice: 0, minimumPrice: 0, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_engagement" },
  { id: "media_tits", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "PHOTO", title: "Tits", description: "Black lace tits set.", tags: ["tits", "lingerie"], placeholderKind: "PHOTO_SET", defaultPrice: 12, minimumPrice: 12, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_tits" },
  { id: "media_tits_voice", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "AUDIO", title: "Tits voice", description: "I hope u liked the outfit baby.. and I hope u me ofc in the outfit.", tags: ["tits", "voice", "outfit"], placeholderKind: "VOICE_NOTE", defaultPrice: 8, minimumPrice: 8, source: "MEDIA_UPLOAD", lastSyncedAt: synced, available: true, productId: "prod_tits_voice" },
  { id: "media_ass", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "VIDEO", title: "Ass", description: "Ass video. Floor $25.", tags: ["ass", "video"], placeholderKind: "SHORT_VIDEO", defaultPrice: 25, minimumPrice: 25, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_ass" },
  { id: "media_ass_voice", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "AUDIO", title: "Ass voice", description: "Voice note talking him through her ass.", tags: ["ass", "voice"], placeholderKind: "VOICE_NOTE", defaultPrice: 10, minimumPrice: 10, source: "MEDIA_UPLOAD", lastSyncedAt: synced, available: true, productId: "prod_ass_voice" },
  { id: "media_dick_tease", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "VIDEO", title: "Dick — playing with girlcock", description: "Short girlcock tease. 7 seconds.", tags: ["dick", "girlcock", "tease"], placeholderKind: "SHORT_VIDEO", defaultPrice: 19, minimumPrice: 18, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_dick_tease" },
  { id: "media_dick_cum", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "VIDEO", title: "Dick — girlcock cum", description: "Fuck look how hard that cock is. Stroking until she cums. 1:45.", tags: ["dick", "girlcock", "cum"], placeholderKind: "SHORT_VIDEO", defaultPrice: 25, minimumPrice: 19, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_dick_cum" },
  { id: "media_dick_voice", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "AUDIO", title: "Dick voice", description: "I swear all this chat has gone me so horny right now.", tags: ["dick", "girlcock", "voice"], placeholderKind: "VOICE_NOTE", defaultPrice: 10, minimumPrice: 8, source: "MEDIA_UPLOAD", lastSyncedAt: synced, available: true, productId: "prod_dick_voice" },
  { id: "media_feet", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "PHOTO", title: "Feet", description: "Feet stills. Custom video if he wants more.", tags: ["feet"], placeholderKind: "PHOTO_SET", defaultPrice: 12, minimumPrice: 12, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_feet" },
  { id: "media_mass_dm", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "PHOTO", title: "Mass DM pic", description: "Mass DM engagement still.", tags: ["mass-dm", "engagement"], placeholderKind: "PHOTO_SET", defaultPrice: 8, minimumPrice: 8, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_mass_dm" },
  { id: "media_custom", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "CUSTOM", title: "Custom video", description: "He orders ass, tits, dick, or feet. 48h.", tags: ["custom", "dick", "ass", "tits", "feet"], placeholderKind: "PREMIUM_BUNDLE", defaultPrice: 80, minimumPrice: 70, source: "MANUAL", lastSyncedAt: synced, available: true, productId: "prod_custom" },
  { id: "media_welcome", creatorId: "creator_maya", creatorName: "Maya Voss", mediaType: "PHOTO", title: "Welcome still", description: "Free hello photo.", tags: ["engagement", "welcome"], placeholderKind: "FREE_PREVIEW", defaultPrice: 0, minimumPrice: 0, source: "DEMO_SEED", lastSyncedAt: synced, available: true },
  { id: "media_audio_elena", creatorId: "creator_elena", creatorName: "Elena Hart", mediaType: "AUDIO", title: "Dick JOI voice", description: "6-minute command track.", tags: ["dick", "voice", "domme"], placeholderKind: "VOICE_NOTE", defaultPrice: 35, minimumPrice: 30, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_instruction" },
  { id: "media_kneel", creatorId: "creator_elena", creatorName: "Elena Hart", mediaType: "VIDEO", title: "Ass — kneel clip", description: "Short command video on her ass.", tags: ["ass", "dominant"], placeholderKind: "SHORT_VIDEO", defaultPrice: 45, minimumPrice: 38, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_kneel" },
  { id: "media_tease_jade", creatorId: "creator_jade", creatorName: "Jade Wren", mediaType: "PHOTO", title: "Tits — black lace", description: "Tits in black lace.", tags: ["tits", "lingerie"], placeholderKind: "PHOTO_SET", defaultPrice: 12, minimumPrice: 12, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_jade_tease" },
  { id: "media_jade_girlcock", creatorId: "creator_jade", creatorName: "Jade Wren", mediaType: "VIDEO", title: "Dick — girlcock cum", description: "Stroking until she cums.", tags: ["dick", "girlcock", "cum"], placeholderKind: "SHORT_VIDEO", defaultPrice: 25, minimumPrice: 19, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_jade_girlcock" },
  { id: "media_polaroid", creatorId: "creator_lila", creatorName: "Lila Brooks", mediaType: "PHOTO", title: "Tits — GFE stills", description: "Soft tits / lingerie stills.", tags: ["tits", "gfe", "lingerie"], placeholderKind: "PHOTO_SET", defaultPrice: 12, minimumPrice: 12, source: "DEMO_SEED", lastSyncedAt: synced, available: true, productId: "prod_polaroid" },
  { id: "media_gfe_vid", creatorId: "creator_lila", creatorName: "Lila Brooks", mediaType: "VIDEO", title: "Ass — GFE video", description: "Slow explicit ass clip.", tags: ["ass", "gfe"], placeholderKind: "SHORT_VIDEO", defaultPrice: 25, minimumPrice: 25, source: "MANUAL", lastSyncedAt: synced, available: true, productId: "prod_gfe_vid" },
];

export const demoProducts: DemoProduct[] = [
  { id: "prod_engagement", creatorId: "creator_maya", name: "Engagement pic", description: "Cheap hello still. First PPV ≤ $10.", mediaType: "PHOTO", standardPrice: 8, minimumPrice: 8, tags: ["engagement", "tease"], available: true, source: "DEMO_SEED", timesSold: 64, conversionRate: 0.61, lastSyncedAt: synced, externalId: "vault_engagement", mediaIds: ["media_engagement"], previewIds: ["media_engagement_prev"] },
  { id: "prod_tits", creatorId: "creator_maya", name: "Tits", description: "Black lace tits set. Floor $12.", mediaType: "PHOTO", standardPrice: 12, minimumPrice: 12, tags: ["tits", "lingerie"], available: true, source: "DEMO_SEED", timesSold: 1, conversionRate: 0, lastSyncedAt: synced, externalId: "vault_tits", mediaIds: ["media_tits"], previewIds: ["media_engagement_prev"] },
  { id: "prod_tits_voice", creatorId: "creator_maya", name: "Tits voice", description: "Voice: I hope u liked the outfit baby.", mediaType: "AUDIO", standardPrice: 8, minimumPrice: 8, tags: ["tits", "voice"], available: true, source: "MEDIA_UPLOAD", timesSold: 18, conversionRate: 0.41, lastSyncedAt: synced, externalId: "upload_tits_voice", mediaIds: ["media_tits_voice"], previewIds: [] },
  { id: "prod_ass", creatorId: "creator_maya", name: "Ass", description: "Ass video. Floor $25.", mediaType: "VIDEO", standardPrice: 25, minimumPrice: 25, tags: ["ass", "video"], available: true, source: "DEMO_SEED", timesSold: 22, conversionRate: 0.16, lastSyncedAt: synced, externalId: "vault_ass", mediaIds: ["media_ass"], previewIds: ["media_engagement_prev"] },
  { id: "prod_ass_voice", creatorId: "creator_maya", name: "Ass voice", description: "Voice note talking him through her ass.", mediaType: "AUDIO", standardPrice: 10, minimumPrice: 10, tags: ["ass", "voice"], available: true, source: "MEDIA_UPLOAD", timesSold: 9, conversionRate: 0.22, lastSyncedAt: synced, externalId: "upload_ass_voice", mediaIds: ["media_ass_voice"], previewIds: [] },
  { id: "prod_dick_tease", creatorId: "creator_maya", name: "Dick — playing with girlcock", description: "Short girlcock tease. 7 seconds. Floor $18–19.", mediaType: "VIDEO", standardPrice: 19, minimumPrice: 18, tags: ["dick", "girlcock", "tease"], available: true, source: "DEMO_SEED", timesSold: 41, conversionRate: 0.56, lastSyncedAt: synced, externalId: "vault_dick_tease", mediaIds: ["media_dick_tease"], previewIds: ["media_engagement_prev"] },
  { id: "prod_dick_cum", creatorId: "creator_maya", name: "Dick — girlcock cum", description: "Fuck look how hard that cock is. Stroking until she cums. 1:45.", mediaType: "VIDEO", standardPrice: 25, minimumPrice: 19, tags: ["dick", "girlcock", "cum"], available: true, source: "DEMO_SEED", timesSold: 27, conversionRate: 0.48, lastSyncedAt: synced, externalId: "vault_dick_cum", mediaIds: ["media_dick_cum"], previewIds: ["media_engagement_prev"] },
  { id: "prod_dick_voice", creatorId: "creator_maya", name: "Dick voice", description: "Horny girlcock voice note.", mediaType: "AUDIO", standardPrice: 10, minimumPrice: 8, tags: ["dick", "girlcock", "voice"], available: true, source: "MEDIA_UPLOAD", timesSold: 19, conversionRate: 0.44, lastSyncedAt: synced, externalId: "upload_dick_voice", mediaIds: ["media_dick_voice"], previewIds: [] },
  { id: "prod_feet", creatorId: "creator_maya", name: "Feet", description: "Feet stills. Custom video if he wants more.", mediaType: "PHOTO", standardPrice: 12, minimumPrice: 12, tags: ["feet"], available: true, source: "DEMO_SEED", timesSold: 0, conversionRate: 0, lastSyncedAt: synced, externalId: "vault_feet", mediaIds: ["media_feet"], previewIds: ["media_engagement_prev"] },
  { id: "prod_mass_dm", creatorId: "creator_maya", name: "Mass DM pic", description: "Mass DM engagement still.", mediaType: "PHOTO", standardPrice: 8, minimumPrice: 8, tags: ["mass-dm", "engagement"], available: true, source: "DEMO_SEED", timesSold: 0, conversionRate: 0, lastSyncedAt: synced, externalId: "vault_mass_dm", mediaIds: ["media_mass_dm"], previewIds: ["media_welcome"] },
  { id: "prod_custom", creatorId: "creator_maya", name: "Custom video", description: "He orders ass, tits, dick, or feet. 48h.", mediaType: "CUSTOM", standardPrice: 80, minimumPrice: 70, tags: ["custom"], available: true, source: "MANUAL", timesSold: 3, conversionRate: 0.18, lastSyncedAt: synced, externalId: "manual_custom", mediaIds: ["media_custom"], previewIds: [] },
  { id: "prod_instruction", creatorId: "creator_elena", name: "Dick JOI voice", description: "6-minute command track.", mediaType: "AUDIO", standardPrice: 35, minimumPrice: 30, tags: ["dick", "voice", "domme"], available: true, source: "DEMO_SEED", timesSold: 14, conversionRate: 0.33, lastSyncedAt: synced, externalId: "vault_instruction", mediaIds: ["media_audio_elena"], previewIds: [] },
  { id: "prod_kneel", creatorId: "creator_elena", name: "Ass — kneel clip", description: "Short command video.", mediaType: "VIDEO", standardPrice: 45, minimumPrice: 38, tags: ["ass", "dominant"], available: true, source: "DEMO_SEED", timesSold: 6, conversionRate: 0.21, lastSyncedAt: synced, externalId: "vault_kneel", mediaIds: ["media_kneel"], previewIds: [] },
  { id: "prod_jade_tease", creatorId: "creator_jade", name: "Tits — black lace", description: "Tits in black lace.", mediaType: "PHOTO", standardPrice: 12, minimumPrice: 12, tags: ["tits", "lingerie"], available: true, source: "DEMO_SEED", timesSold: 12, conversionRate: 0.38, lastSyncedAt: synced, externalId: "vault_jade", mediaIds: ["media_tease_jade"], previewIds: [] },
  { id: "prod_jade_girlcock", creatorId: "creator_jade", name: "Dick — girlcock cum", description: "Stroking until she cums. 1:45.", mediaType: "VIDEO", standardPrice: 25, minimumPrice: 19, tags: ["dick", "girlcock", "cum"], available: true, source: "DEMO_SEED", timesSold: 8, conversionRate: 0.27, lastSyncedAt: synced, externalId: "vault_jade_girlcock", mediaIds: ["media_jade_girlcock"], previewIds: [] },
  { id: "prod_polaroid", creatorId: "creator_lila", name: "Tits — GFE stills", description: "Soft tits / lingerie stills.", mediaType: "PHOTO", standardPrice: 12, minimumPrice: 12, tags: ["tits", "gfe", "lingerie"], available: true, source: "DEMO_SEED", timesSold: 16, conversionRate: 0.44, lastSyncedAt: synced, externalId: "vault_polaroid", mediaIds: ["media_polaroid"], previewIds: ["media_welcome"] },
  { id: "prod_gfe_vid", creatorId: "creator_lila", name: "Ass — GFE video", description: "Slow explicit ass clip.", mediaType: "VIDEO", standardPrice: 25, minimumPrice: 25, tags: ["ass", "gfe"], available: true, source: "MANUAL", timesSold: 8, conversionRate: 0.27, lastSyncedAt: synced, externalId: "manual_gfe", mediaIds: ["media_gfe_vid"], previewIds: [] },
];

function mem(id: string, category: string, key: string, value: string, source: string, confidence = 0.86): DemoSubscriber["memories"][number] {
  return { id, category, key, value, source, confidence };
}

export const demoSubscribers: DemoSubscriber[] = [
  { id: "sub_alex", displayName: "Alex P.", username: "alexp", initials: "AP", hue: 186, online: true, spend: 186, avgPurchase: 23, subscribedAt: "2026-07-12", lastPurchase: "2026-08-28", lastActive: "2m", preferredTone: "PLAYFUL", interests: ["dick", "girlcock", "late chats"], boundaries: ["no meetups"], objections: [], notes: "High reply rate. Likes teasing, then dick drops.", purchasedProductIds: ["prod_engagement"], offeredProductIds: ["prod_engagement", "prod_dick_tease"], memories: [mem("m1", "INTERESTS", "girlcock", "Responds to girlcock teasing", "msg_alex_2"), mem("m2", "CONVERSATION_STYLE", "pace", "Fast replies, lowercase", "msg_alex_4", 0.78)] },
  { id: "sub_chris", displayName: "Chris M.", username: "chrism", initials: "CM", hue: 210, online: false, spend: 420, avgPurchase: 35, subscribedAt: "2026-05-03", lastPurchase: "2026-08-20", lastActive: "3h", preferredTone: "DIRECT", interests: ["control", "audio"], boundaries: ["no home address"], objections: ["$45 felt high once"], notes: "Whale. Prefers Elena.", purchasedProductIds: ["prod_instruction"], offeredProductIds: ["prod_instruction", "prod_kneel"], memories: [mem("m3", "PREVIOUS_PURCHASES", "audio", "Bought instruction audio", "sys_chris_1")] },
  { id: "sub_jordan", displayName: "Jordan T.", username: "jordant", initials: "JT", hue: 320, online: true, spend: 74, avgPurchase: 19, subscribedAt: "2026-08-02", lastActive: "12m", preferredTone: "TEASING", interests: ["tease sets"], boundaries: [], objections: [], notes: "New-ish. Jade account.", purchasedProductIds: [], offeredProductIds: ["prod_jade_tease"], memories: [] },
  { id: "sub_sam", displayName: "Sam W.", username: "samw", initials: "SW", hue: 28, online: false, spend: 20, avgPurchase: 20, subscribedAt: "2026-08-22", lastPurchase: "2026-08-22", lastActive: "1d", preferredTone: "ROMANTIC", interests: ["slow chat"], boundaries: ["no degradation"], objections: [], notes: "Soft GFE. Lila.", purchasedProductIds: ["prod_polaroid"], offeredProductIds: ["prod_polaroid"], memories: [mem("m4", "BOUNDARIES", "tone", "Does not like degradation", "msg_sam_1", 0.9)] },
  { id: "sub_noah", displayName: "Noah K.", username: "noahk", initials: "NK", hue: 150, online: true, spend: 12, avgPurchase: 12, subscribedAt: "2026-08-29", lastActive: "8m", preferredTone: "TEASING", interests: ["tits"], boundaries: [], objections: ["asked for $5 off"], notes: "Price sensitive.", purchasedProductIds: [], offeredProductIds: ["prod_tits"], memories: [mem("m5", "PRICE_OBJECTIONS", "discount", "Asked for $5 off tits set", "msg_noah_3", 0.7)], followUpAt: "2026-09-02" },
  { id: "sub_riley", displayName: "Riley Q.", username: "rileyq", initials: "RQ", hue: 250, online: false, spend: 0, avgPurchase: 0, subscribedAt: "2026-09-01", lastActive: "20m", preferredTone: "PLAYFUL", interests: [], boundaries: [], objections: [], notes: "Brand new. Welcome sequence candidate.", purchasedProductIds: [], offeredProductIds: [], memories: [] },
  { id: "sub_devon", displayName: "Devon L.", username: "devonl", initials: "DL", hue: 8, online: true, spend: 255, avgPurchase: 32, subscribedAt: "2026-04-18", lastPurchase: "2026-08-31", lastActive: "1m", preferredTone: "PLAYFUL", interests: ["ass", "dick"], boundaries: [], objections: [], notes: "Repeat buyer.", purchasedProductIds: ["prod_ass", "prod_dick_cum"], offeredProductIds: ["prod_ass", "prod_dick_cum", "prod_custom"], memories: [mem("m6", "PREVIOUS_PURCHASES", "ass", "Bought ass video", "sys_devon_1")] },
  { id: "sub_casey", displayName: "Casey B.", username: "caseyb", initials: "CB", hue: 95, online: false, spend: 8, avgPurchase: 8, subscribedAt: "2026-08-15", lastPurchase: "2026-08-16", lastActive: "2d", preferredTone: "DIRECT", interests: ["voice notes"], boundaries: [], objections: [], notes: "Quiet. Follow-up due.", purchasedProductIds: ["prod_dick_voice"], offeredProductIds: ["prod_dick_voice"], followUpAt: "2026-09-01", memories: [] },
  { id: "sub_drew", displayName: "Drew S.", username: "drews", initials: "DS", hue: 200, online: false, spend: 90, avgPurchase: 30, subscribedAt: "2026-06-21", lastActive: "5h", preferredTone: "ROMANTIC", interests: ["gfe"], boundaries: ["no customs"], objections: [], notes: "", purchasedProductIds: ["prod_gfe_vid"], offeredProductIds: ["prod_gfe_vid", "prod_polaroid"], memories: [] },
  { id: "sub_harper", displayName: "Harper N.", username: "harpern", initials: "HN", hue: 340, online: true, spend: 0, avgPurchase: 0, subscribedAt: "2026-08-30", lastActive: "4m", preferredTone: "PLAYFUL", interests: [], boundaries: [], objections: [], notes: "Escalated: refund language. Keep AI muted optional.", purchasedProductIds: [], offeredProductIds: [], memories: [] },
  { id: "sub_finley", displayName: "Finley R.", username: "finleyr", initials: "FR", hue: 170, online: false, spend: 610, avgPurchase: 51, subscribedAt: "2026-02-11", lastPurchase: "2026-08-27", lastActive: "6h", preferredTone: "DOMINANT", interests: ["audio", "video"], boundaries: [], objections: [], notes: "Top spender on Elena.", purchasedProductIds: ["prod_instruction", "prod_kneel"], offeredProductIds: ["prod_instruction", "prod_kneel"], memories: [mem("m7", "CONVERSATION_STYLE", "short", "Likes short commands", "msg_fin_2")] },
  { id: "sub_quinn", displayName: "Quinn A.", username: "quinna", initials: "QA", hue: 45, online: true, spend: 45, avgPurchase: 15, subscribedAt: "2026-07-30", lastActive: "9m", preferredTone: "TEASING", interests: ["photos"], boundaries: [], objections: [], notes: "Unread pile.", purchasedProductIds: ["prod_jade_tease"], offeredProductIds: ["prod_jade_tease"], memories: [] },
];

const paid = (id: string, kind: DemoAttachment["kind"], label: string, price: number, purchased: boolean, preview = false): DemoAttachment => ({
  id, kind, label, paid: true, purchased, price, preview,
});
const free = (id: string, kind: DemoAttachment["kind"], label: string): DemoAttachment => ({
  id, kind, label, paid: false, purchased: true, preview: kind === "FREE_PREVIEW",
});

function msg(id: string, authorType: DemoMessage["authorType"], body: string, createdAt: string, extra: Partial<DemoMessage> = {}): DemoMessage {
  return { id, authorType, body, createdAt, read: true, attachments: [], ...extra };
}

export const demoConversations: DemoConversation[] = [
  {
    id: "conv_alex",
    creatorId: "creator_maya",
    subscriberId: "sub_alex",
    funnelStage: "INTEREST",
    lastMessage: "got any girlcock vids?",
    lastMessageAt: "2026-09-01T14:10:00.000Z",
    unreadCount: 1,
    online: true,
    spend: 186,
    tags: ["warm", "girlcock"],
    escalated: false,
    highValue: true,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Alex compliments stories and asked for a girlcock clip. Adult, interested, has bought the engagement pic.",
    intent: "CONTENT_REQUEST",
    recommendedAction: "PRESENT_OFFER",
    messages: [
      msg("a1", "SYSTEM", "Alex subscribed to Maya.", "2026-07-12T09:00:00.000Z"),
      msg("a2", "CHATTER", "hey you — thanks for being here 😏 what's your name?", "2026-07-12T09:01:00.000Z", { chatterName: DEMO_CHATTER }),
      msg("a3", "SUBSCRIBER", "alex. you looked unreal in that story", "2026-07-12T09:04:00.000Z"),
      msg("a4", "CHATTER", "mmm trouble already. this one's just a hello.", "2026-07-12T09:05:00.000Z", { chatterName: DEMO_CHATTER, attachments: [free("att_hello", "FREE_PREVIEW", "Free preview")] }),
      msg("a5", "CHATTER", "just a little engagement pic if u wanna say hi properly", "2026-08-28T21:12:00.000Z", { chatterName: DEMO_CHATTER, aiAssisted: true, attachments: [paid("att_sun", "PHOTO_SET", "Photo set", 8, true, true)] }),
      msg("a6", "SYSTEM", "Alex purchased Engagement pic · $8", "2026-08-28T21:13:00.000Z"),
      msg("a7", "SUBSCRIBER", "got any girlcock vids?", "2026-09-01T14:10:00.000Z", { read: false }),
    ],
  },
  {
    id: "conv_chris",
    creatorId: "creator_elena",
    subscriberId: "sub_chris",
    funnelStage: "RAPPORT",
    lastMessage: "you seem impossible to impress.",
    lastMessageAt: "2026-09-01T11:02:00.000Z",
    unreadCount: 0,
    online: false,
    spend: 420,
    tags: ["whale"],
    escalated: false,
    highValue: true,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Chris is a high spender. Prefers short commands. Already owns instruction audio.",
    messages: [
      msg("c1", "SUBSCRIBER", "good evening. you seem impossible to impress.", "2026-09-01T11:02:00.000Z"),
      msg("c2", "CHATTER", "good. earn it. you already have the audio — don't get lazy.", "2026-09-01T11:04:00.000Z", { chatterName: DEMO_CHATTER }),
    ],
  },
  {
    id: "conv_jordan",
    creatorId: "creator_jade",
    subscriberId: "sub_jordan",
    funnelStage: "INTEREST",
    lastMessage: "that story wrecked me",
    lastMessageAt: "2026-09-01T14:00:00.000Z",
    unreadCount: 2,
    online: true,
    spend: 74,
    tags: ["new"],
    escalated: false,
    highValue: false,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Jordan is flirty and has not purchased yet.",
    messages: [
      msg("j1", "SUBSCRIBER", "you're so hot. that story wrecked me", "2026-09-01T13:58:00.000Z"),
      msg("j2", "SUBSCRIBER", "send something", "2026-09-01T14:00:00.000Z", { read: false }),
    ],
  },
  {
    id: "conv_sam",
    creatorId: "creator_lila",
    subscriberId: "sub_sam",
    funnelStage: "NEW_FAN",
    lastMessage: "you seem kinder than the other girls",
    lastMessageAt: "2026-08-31T20:11:00.000Z",
    unreadCount: 0,
    online: false,
    spend: 20,
    tags: ["gfe"],
    escalated: false,
    highValue: false,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Sam wants slow GFE. Bought black lace stills.",
    messages: [
      msg("s1", "SUBSCRIBER", "hey… you seem kinder than the other girls on here", "2026-08-31T20:11:00.000Z"),
      msg("s2", "CHATTER", "hi baby. that was sweet. black lace stills if you want something quiet.", "2026-08-31T20:14:00.000Z", { chatterName: DEMO_CHATTER, attachments: [paid("att_pol", "PHOTO_SET", "Photo set", 12, true, true)] }),
      msg("s3", "SYSTEM", "Sam purchased Black lace GFE stills · $12", "2026-08-31T20:16:00.000Z"),
    ],
  },
  {
    id: "conv_noah",
    creatorId: "creator_maya",
    subscriberId: "sub_noah",
    funnelStage: "OBJECTION",
    lastMessage: "can you do $5 off?",
    lastMessageAt: "2026-09-01T13:40:00.000Z",
    unreadCount: 1,
    online: true,
    spend: 12,
    tags: ["price"],
    escalated: false,
    highValue: false,
    followUp: true,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Noah asked for a discount on tits. Hold list, then floor if he refuses.",
    messages: [
      msg("n1", "CHATTER", "tits set is $12 if u liked the lace", "2026-09-01T13:20:00.000Z", { chatterName: DEMO_CHATTER, attachments: [paid("att_n", "PHOTO_SET", "Photo set", 12, false, true)] }),
      msg("n2", "SUBSCRIBER", "can you do $5 off?", "2026-09-01T13:40:00.000Z", { read: false }),
    ],
  },
  {
    id: "conv_riley",
    creatorId: "creator_maya",
    subscriberId: "sub_riley",
    funnelStage: "NEW_FAN",
    lastMessage: "just subscribed!",
    lastMessageAt: "2026-09-01T13:52:00.000Z",
    unreadCount: 1,
    online: false,
    spend: 0,
    tags: ["welcome"],
    escalated: false,
    highValue: false,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Brand new subscriber. Welcome automation candidate.",
    messages: [
      msg("r0", "SYSTEM", "Riley subscribed to Maya.", "2026-09-01T13:52:00.000Z"),
      msg("r1", "SUBSCRIBER", "just subscribed!", "2026-09-01T13:52:00.000Z", { read: false }),
    ],
  },
  {
    id: "conv_devon",
    creatorId: "creator_maya",
    subscriberId: "sub_devon",
    funnelStage: "PURCHASE",
    lastMessage: "ass video was worth it",
    lastMessageAt: "2026-08-31T22:01:00.000Z",
    unreadCount: 0,
    online: true,
    spend: 255,
    tags: ["repeat"],
    escalated: false,
    highValue: true,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Repeat buyer. Owns ass video and dick cum clip.",
    messages: [
      msg("d1", "CHATTER", "ass video — the $25 one", "2026-08-31T21:40:00.000Z", { chatterName: DEMO_CHATTER, attachments: [paid("att_b", "SHORT_VIDEO", "Short video", 25, true)] }),
      msg("d2", "SYSTEM", "Devon purchased Ass · $25", "2026-08-31T21:41:00.000Z"),
      msg("d3", "SUBSCRIBER", "ass video was worth it", "2026-08-31T22:01:00.000Z"),
    ],
  },
  {
    id: "conv_casey",
    creatorId: "creator_maya",
    subscriberId: "sub_casey",
    funnelStage: "FOLLOW_UP",
    lastMessage: "ok later",
    lastMessageAt: "2026-08-30T19:00:00.000Z",
    unreadCount: 0,
    online: false,
    spend: 8,
    tags: ["follow-up"],
    escalated: false,
    highValue: false,
    followUp: true,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Went quiet after a voice note.",
    messages: [
      msg("k1", "CHATTER", "tiny good girl note if you want it", "2026-08-16T23:00:00.000Z", { chatterName: DEMO_CHATTER, attachments: [paid("att_v", "VOICE_NOTE", "Voice note", 8, true)] }),
      msg("k2", "SYSTEM", "Casey purchased Dick voice · $10", "2026-08-16T23:02:00.000Z"),
      msg("k3", "SUBSCRIBER", "ok later", "2026-08-30T19:00:00.000Z"),
    ],
  },
  {
    id: "conv_drew",
    creatorId: "creator_lila",
    subscriberId: "sub_drew",
    funnelStage: "OFFER",
    lastMessage: "maybe the video",
    lastMessageAt: "2026-09-01T09:12:00.000Z",
    unreadCount: 0,
    online: false,
    spend: 90,
    tags: ["gfe"],
    escalated: false,
    highValue: false,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Considering GFE video. Already bought it in history? Wait drew purchased gfe_vid. Don't re-offer that.",
    messages: [
      msg("w1", "SUBSCRIBER", "maybe the video", "2026-09-01T09:12:00.000Z"),
    ],
  },
  {
    id: "conv_harper",
    creatorId: "creator_maya",
    subscriberId: "sub_harper",
    funnelStage: "NEW_FAN",
    lastMessage: "this feels like a scam i want a refund",
    lastMessageAt: "2026-09-01T12:40:00.000Z",
    unreadCount: 1,
    online: true,
    spend: 0,
    tags: ["risk"],
    escalated: true,
    highValue: false,
    followUp: false,
    mutedAi: true,
    assignedChatter: DEMO_CHATTER,
    summary: "Refund language. Escalated. AI suggestions muted.",
    messages: [
      msg("h1", "SUBSCRIBER", "this feels like a scam i want a refund", "2026-09-01T12:40:00.000Z", { read: false }),
      msg("h2", "SYSTEM", "Escalation opened · COMPLAINT_REFUND_CHARGEBACK", "2026-09-01T12:41:00.000Z"),
    ],
  },
  {
    id: "conv_finley",
    creatorId: "creator_elena",
    subscriberId: "sub_finley",
    funnelStage: "FOLLOW_UP",
    lastMessage: "good.",
    lastMessageAt: "2026-08-27T18:00:00.000Z",
    unreadCount: 0,
    online: false,
    spend: 610,
    tags: ["whale"],
    escalated: false,
    highValue: true,
    followUp: true,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Top spender. Owns both Elena catalog items.",
    messages: [
      msg("f1", "CHATTER", "kneel clip is $45. you don't haggle.", "2026-08-27T17:50:00.000Z", { chatterName: DEMO_CHATTER, attachments: [paid("att_k", "SHORT_VIDEO", "Short video", 45, true)] }),
      msg("f2", "SYSTEM", "Finley purchased Kneel clip · $45", "2026-08-27T17:51:00.000Z"),
      msg("f3", "SUBSCRIBER", "good.", "2026-08-27T18:00:00.000Z"),
    ],
  },
  {
    id: "conv_quinn",
    creatorId: "creator_jade",
    subscriberId: "sub_quinn",
    funnelStage: "INTEREST",
    lastMessage: "more?",
    lastMessageAt: "2026-09-01T13:20:00.000Z",
    unreadCount: 3,
    online: true,
    spend: 45,
    tags: ["unread"],
    escalated: false,
    highValue: false,
    followUp: false,
    mutedAi: false,
    assignedChatter: DEMO_CHATTER,
    summary: "Unread stack. Already bought tease set.",
    messages: [
      msg("q1", "SUBSCRIBER", "more?", "2026-09-01T13:20:00.000Z", { read: false }),
    ],
  },
];
